# --- Configurações do H2 Database (Modo Arquivo/Persistente) ---

# Salva os dados na pasta './data/firecheckdb' dentro do projeto
spring.datasource.url=jdbc:h2:file:./data/firecheckdb

# Driver e Usuário (padrão)
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o console para você ver o banco no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- Configurações do JPA (Hibernate) ---

# Dialeto do banco
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# IMPORTANTE: 'update' mantém os dados e só cria tabelas se não existirem
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console (útil para debug)
spring.jpa.show-sql=true

# --- Configurações de E-mail (Exemplo: Gmail) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Coloque aqui o e-mail real que vai disparar as mensagens
spring.mail.username=projetofirecheck@gmail.com
# Coloque aqui a "Senha de Aplicativo" de 16 dígitos gerada no Google
spring.mail.password=upszpqlokzskmuei
# Propriedades de segurança do servidor de e-mail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true